"""Default scoring weights for contribution quality checks."""

ACTIONABLE_POINTS = 30
VERIFICATION_POINTS = 25
CONTEXT_POINTS = 15
RISK_POINTS = 15
DEVELOPER_CHECK_POINTS = 15

READY_THRESHOLD = 80
NEEDS_POLISH_THRESHOLD = 55
